sudo: false
script: mvn clean install

after_success:
  - .buildscript/deploy_snapshot.sh
  
cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - secure: o9RXdFVzIpHcWIE9JM50pC82jOSnMBMSERnRwEtcnXwdWFu5+XWNO9veXKEY8UkfFF/hzdTtZoFe5KVDPqvf6QCJ3Osm0Ax/T2/t/qwxhBCNDqBtxi4/GEF+K14MRd/3bR2HMWF+dtIhOwP3cdOcMnqWY2BOwGcxWNNTo/K8Li96DdHzGporqKzi/4Q3GvDd5VXY0PJ3uG0nK2CKh5fa7XSPNU/1XjReAVCNL5PIqCte7AH9wgRkgC5nQfLEf6ljSIPrdLzsBmqyH30KiU4P4m8SWv6qipg9ruNxFGU3nSj/IClY2xx1vOhoJCD5klhx7NskUtL2rwv0egoM+REbidmHIg23slm5FLCpMQNDwBCXwH+jCPWA8Liyqzp/zYvv81z0+I+Yh+8uYtOhDGbMk9bMEQfFxvJ18M/GGfXfu0ffbZyPaiUybNZquoi1J7cieEs8cmU5wiL5Jx30aqiQDNBlAOF0LGNSLaD4NiRdyvVO/X3fhhQGVqLy9WO2q1cl1O72uAQvcCkyAG8yKeHsiRg97Dx4NLyraqKqcSxzYpQ/3GSm9fZ8xh7BDjSQsTaZ0uAq5UlLChuzxRuwn56CzrJbwZRH20k0gABe3vfgAUeQE2cJiFJlr00AYy5hQ0uzvoOOSft9Sbh0miSGzMkKvdTZevlK8xMRCZpYM0oMIr8=
  - secure: Ck7bH/+wew+vJ683Pn1OFUlGHoCMJyPRGfHV81xFaboFkyUE1xEgfz2aDAYI01cy6tllKWAEkr6+znAtjcD3pdnAP7geCjQoOn0VJVtYQRWjMaCR07MUlDbq/8k9NSZjSjMfzQ0l7Bm5HmzVRbUjIsNeyTa4yD6P3/Hx++msMMdJUdykvFCvG/QqvNnnQys5rXJvibx0b57weoCRLOw7fRjZQO2MSze/klZzqF3IBQEfxTlhrLssY7P1pdwK8C4I3v0selandjHZZMMjQdA50Hk/gccuyF1+lq1RMAGea6QI//4vXCnp79NPPw6L4TUC1U8hQfxX9NWD6Ecb0aiFuhIeAUy/pxwrZha3HWWWfo1lR6Fg9KtuTXAmFX5ekNxbkmS7eQ53bJaNBXWzloWvU51nZqETaiyLZN5u3LdDif2w/KRVrs3HB2LLeRqeQ+iMFMZAvo20YQ8TDz+nPm6XcjSIT6DDvwZu9+yythiGC4apHIFDQPbpfu2Gx+WgzXupGa03Tp8UEpHHCWFtSc2/oMApHcHXDtMRDjN3eIC4Hm0YlpKfVMNB/9mGWcIgOf3T1VuuKrMRVmkNgTa33IBnX7nd0NY6ynSqmy+U+ZK7I4x64H/xgI4lV4pzzAaaCfWvpxh/foPQIsFLM0OvV3KPG4Jwf5TNWt/2oZGbVOS/g/s=
